[build-system]
requires = [ "poetry-core", "setuptools",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = true
name = "py_vyrtuous"
version = "2.8.9"
description = ""
license = "GPL-3.0-or-later"
authors = [ "Brandon Graham Cobb <brandongrahamcobb@icloud.com>",]
readme = "README.md"
homepage = "https://brandongcobb.com"
repository = "https://github.com/brandongrahamcobb/lucy.git"
keywords = [ "chemistry", "Discord", "json", "python", "yaml",]

[tool.poetry.dependencies]
python = "~3.13.1"
rdkit = "^2024.9.1"
aiohttp = "^3.11.11"
asyncpg = "^0.30.0"
bs4 = "^0.0.2"
discord = "^2.3.2"
opencv-python = "^4.10.0.84"
pyqt5 = "^5.15.11"
pubchempy = "^1.0.4"
pyyaml = "^6.0.2"
requests = "^2.32.3"
selenium = "^4.27.1"
quart = "^0.20.0"
webdriver-manager = "^4.0.2"
toml = "^0.10.2"
audioop-lts = "^0.2.1"
pytz = "^2024.2"
discord-ext-menus = "^1.1"
google-api-python-client = "^2.160.0"
gradio-client = "^1.8.0"
[tool.poetry.scripts]
py_vyrtuous = "py_vyrtuous.main:run"

[tool.poetry.dependencies.discord-py]
extras = [ "voice",]
version = "^2.5.2"

[tool.poetry.dependencies.pypept]
git = "https://github.com/Boehringer-Ingelheim/pyPept.git"
